version: '3.8'

services:
  hello-eyego:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-eyego-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hello-eyego-network

networks:
  hello-eyego-network:
    driver: bridge
